NAME: "onpaper"
MODE: "release"
HOST: "https://localhost"
PORT: 7979
VERSION: "1.0.0"
PUBLICKEY_PATH: "./key/public.key"
PRIVATEKEY_PATH: "./key/private.key"

Mysql:
  HOST: ""
  PORT: 3306
  DATABASE: ""
  USER: ""
  PASSWORD: ""
  MAX_OPEN_CONNS: 500
  MAX_IDLE_CONNS: 50

Redis:
  ADDR:
  USERNAME: ""
  PASSWORD: ""
  POOL_SIZE: 2000

MongoDB:
  HOST:
  USER:
  PASSWORD:
  DATABASE: ""
  POOL_SIZE: 500

Log:
  LEVEL: "info"
  FILENAME: "./logger/web_app.log"
  MAX_SIZE: 200
  MAX_AGE: 30
  MAX_BACKUPS: 7

Oss:
  AppId: ""
  # oss 最高权限 用户
  OSS_MAX_SecretId: ""
  OSS_MAX_SecretKey: ""
  # 创建sts 用户
  OSS_STS_SecretId: ""
  OSS_STS_SecretKey: ""
  STS_RoleArn: ""
  Endpoint: ""
  PreviewBucket: ""
  OriginalBucket: ""
  TempBucket: ""

SMS:
  SecretId: ""
  SecretKey: ""
  TemplateCode: ""

SnowFlake:
  Start_Time: "2021-07-01"
  Machine_Id: 1

InvitationCode:
  MagicCode: ""

MiniProgram:
  AppID: ""
  AppSecret: ""
